name: Publish package

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      package-name:
        description: The name of the package
        type: string
      dry-run:
        description: Dry run (no publish)
        type: boolean
        default: true

jobs:
  npm-publish:
    uses: samchungy/langs/.github/workflows/release.yml@main
    with:
      directory: packages/${{inputs.package-name}}
      dry-run: ${{ inputs.dry-run }}
    secrets:
      NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
